language: php
php:
  - 7.2
  - 7.3
  - 7.4

# Cache Composer deps
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - vendor/bin/phpstan analyze src tests
  - vendor/bin/phpunit
